#spring:
#  data:
#    redis:
#      host: 127.0.0.1
#      database: 0
#      port: 6379
#      connect-timeout: 50000
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: root
#    password: root
#    virtual-host: /
