package com.example.spring.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.uid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.sub_id
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private Integer subId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.wxid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String wxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.nickname
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.username
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.usertype
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private Integer usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.integral
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private Integer integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.qdcount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private Integer qdcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.sign_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private BigDecimal signAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.qdlastdt
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String qdlastdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mmpid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String mmpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.pidname
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String pidname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.trjid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String trjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.groupid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.groupwxid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String groupwxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.groupname
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.balance
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.alipayrealname
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String alipayrealname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.alipaynum
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String alipaynum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.regtime
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String regtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.order_sixbit
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String orderSixbit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.jdpid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String jdpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.pddpid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String pddpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.pdd_order_lastbit
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String pddOrderLastbit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.order_num
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.smkey
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private Integer smkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.del
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String del;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.order_date
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String orderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.jinjie1
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String jinjie1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.jinjie2
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String jinjie2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.jinjie3
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String jinjie3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.first_award
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String firstAward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.remark
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.region
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Evaluate_num
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private Integer evaluateNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.avatar
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.openid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.province
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mark
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.customer_remark
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String customerRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.sex
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private Boolean sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.address
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.invite_code
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String inviteCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.withdraw_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private BigDecimal withdrawAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.finished_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private BigDecimal finishedAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.pay_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.useless_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private BigDecimal uselessAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.finished_orders_number
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private Integer finishedOrdersNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.pay_orders_number
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private Integer payOrdersNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.useless_orders_number
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private Integer uselessOrdersNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.sub_withdraw
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private BigDecimal subWithdraw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.tb_user_id
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String tbUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_time
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.tag
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.uid
     *
     * @return the value of member.uid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.uid
     *
     * @param uid the value for member.uid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.sub_id
     *
     * @return the value of member.sub_id
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public Integer getSubId() {
        return subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.sub_id
     *
     * @param subId the value for member.sub_id
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setSubId(Integer subId) {
        this.subId = subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.wxid
     *
     * @return the value of member.wxid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getWxid() {
        return wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.wxid
     *
     * @param wxid the value for member.wxid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setWxid(String wxid) {
        this.wxid = wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.nickname
     *
     * @return the value of member.nickname
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.nickname
     *
     * @param nickname the value for member.nickname
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.username
     *
     * @return the value of member.username
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.username
     *
     * @param username the value for member.username
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.usertype
     *
     * @return the value of member.usertype
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.usertype
     *
     * @param usertype the value for member.usertype
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.integral
     *
     * @return the value of member.integral
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.integral
     *
     * @param integral the value for member.integral
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.qdcount
     *
     * @return the value of member.qdcount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public Integer getQdcount() {
        return qdcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.qdcount
     *
     * @param qdcount the value for member.qdcount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setQdcount(Integer qdcount) {
        this.qdcount = qdcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.sign_amount
     *
     * @return the value of member.sign_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public BigDecimal getSignAmount() {
        return signAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.sign_amount
     *
     * @param signAmount the value for member.sign_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setSignAmount(BigDecimal signAmount) {
        this.signAmount = signAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.qdlastdt
     *
     * @return the value of member.qdlastdt
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getQdlastdt() {
        return qdlastdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.qdlastdt
     *
     * @param qdlastdt the value for member.qdlastdt
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setQdlastdt(String qdlastdt) {
        this.qdlastdt = qdlastdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mmpid
     *
     * @return the value of member.mmpid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getMmpid() {
        return mmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mmpid
     *
     * @param mmpid the value for member.mmpid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setMmpid(String mmpid) {
        this.mmpid = mmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.pidname
     *
     * @return the value of member.pidname
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getPidname() {
        return pidname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.pidname
     *
     * @param pidname the value for member.pidname
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setPidname(String pidname) {
        this.pidname = pidname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.trjid
     *
     * @return the value of member.trjid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getTrjid() {
        return trjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.trjid
     *
     * @param trjid the value for member.trjid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setTrjid(String trjid) {
        this.trjid = trjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.groupid
     *
     * @return the value of member.groupid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.groupid
     *
     * @param groupid the value for member.groupid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.groupwxid
     *
     * @return the value of member.groupwxid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getGroupwxid() {
        return groupwxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.groupwxid
     *
     * @param groupwxid the value for member.groupwxid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setGroupwxid(String groupwxid) {
        this.groupwxid = groupwxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.groupname
     *
     * @return the value of member.groupname
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.groupname
     *
     * @param groupname the value for member.groupname
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.balance
     *
     * @return the value of member.balance
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.balance
     *
     * @param balance the value for member.balance
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.alipayrealname
     *
     * @return the value of member.alipayrealname
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getAlipayrealname() {
        return alipayrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.alipayrealname
     *
     * @param alipayrealname the value for member.alipayrealname
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setAlipayrealname(String alipayrealname) {
        this.alipayrealname = alipayrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.alipaynum
     *
     * @return the value of member.alipaynum
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getAlipaynum() {
        return alipaynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.alipaynum
     *
     * @param alipaynum the value for member.alipaynum
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setAlipaynum(String alipaynum) {
        this.alipaynum = alipaynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.regtime
     *
     * @return the value of member.regtime
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.regtime
     *
     * @param regtime the value for member.regtime
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setRegtime(String regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.order_sixbit
     *
     * @return the value of member.order_sixbit
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getOrderSixbit() {
        return orderSixbit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.order_sixbit
     *
     * @param orderSixbit the value for member.order_sixbit
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setOrderSixbit(String orderSixbit) {
        this.orderSixbit = orderSixbit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.jdpid
     *
     * @return the value of member.jdpid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getJdpid() {
        return jdpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.jdpid
     *
     * @param jdpid the value for member.jdpid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setJdpid(String jdpid) {
        this.jdpid = jdpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.pddpid
     *
     * @return the value of member.pddpid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getPddpid() {
        return pddpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.pddpid
     *
     * @param pddpid the value for member.pddpid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setPddpid(String pddpid) {
        this.pddpid = pddpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.pdd_order_lastbit
     *
     * @return the value of member.pdd_order_lastbit
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getPddOrderLastbit() {
        return pddOrderLastbit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.pdd_order_lastbit
     *
     * @param pddOrderLastbit the value for member.pdd_order_lastbit
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setPddOrderLastbit(String pddOrderLastbit) {
        this.pddOrderLastbit = pddOrderLastbit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.order_num
     *
     * @return the value of member.order_num
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.order_num
     *
     * @param orderNum the value for member.order_num
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.smkey
     *
     * @return the value of member.smkey
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public Integer getSmkey() {
        return smkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.smkey
     *
     * @param smkey the value for member.smkey
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setSmkey(Integer smkey) {
        this.smkey = smkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.del
     *
     * @return the value of member.del
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.del
     *
     * @param del the value for member.del
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setDel(String del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.order_date
     *
     * @return the value of member.order_date
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.order_date
     *
     * @param orderDate the value for member.order_date
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.jinjie1
     *
     * @return the value of member.jinjie1
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getJinjie1() {
        return jinjie1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.jinjie1
     *
     * @param jinjie1 the value for member.jinjie1
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setJinjie1(String jinjie1) {
        this.jinjie1 = jinjie1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.jinjie2
     *
     * @return the value of member.jinjie2
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getJinjie2() {
        return jinjie2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.jinjie2
     *
     * @param jinjie2 the value for member.jinjie2
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setJinjie2(String jinjie2) {
        this.jinjie2 = jinjie2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.jinjie3
     *
     * @return the value of member.jinjie3
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getJinjie3() {
        return jinjie3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.jinjie3
     *
     * @param jinjie3 the value for member.jinjie3
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setJinjie3(String jinjie3) {
        this.jinjie3 = jinjie3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.first_award
     *
     * @return the value of member.first_award
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getFirstAward() {
        return firstAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.first_award
     *
     * @param firstAward the value for member.first_award
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setFirstAward(String firstAward) {
        this.firstAward = firstAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.remark
     *
     * @return the value of member.remark
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.remark
     *
     * @param remark the value for member.remark
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.region
     *
     * @return the value of member.region
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.region
     *
     * @param region the value for member.region
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Evaluate_num
     *
     * @return the value of member.Evaluate_num
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public Integer getEvaluateNum() {
        return evaluateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Evaluate_num
     *
     * @param evaluateNum the value for member.Evaluate_num
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setEvaluateNum(Integer evaluateNum) {
        this.evaluateNum = evaluateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.avatar
     *
     * @return the value of member.avatar
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.avatar
     *
     * @param avatar the value for member.avatar
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.openid
     *
     * @return the value of member.openid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.openid
     *
     * @param openid the value for member.openid
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.province
     *
     * @return the value of member.province
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.province
     *
     * @param province the value for member.province
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mark
     *
     * @return the value of member.mark
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mark
     *
     * @param mark the value for member.mark
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.customer_remark
     *
     * @return the value of member.customer_remark
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getCustomerRemark() {
        return customerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.customer_remark
     *
     * @param customerRemark the value for member.customer_remark
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setCustomerRemark(String customerRemark) {
        this.customerRemark = customerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.sex
     *
     * @return the value of member.sex
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.sex
     *
     * @param sex the value for member.sex
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.address
     *
     * @return the value of member.address
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.address
     *
     * @param address the value for member.address
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.invite_code
     *
     * @return the value of member.invite_code
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.invite_code
     *
     * @param inviteCode the value for member.invite_code
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.withdraw_amount
     *
     * @return the value of member.withdraw_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public BigDecimal getWithdrawAmount() {
        return withdrawAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.withdraw_amount
     *
     * @param withdrawAmount the value for member.withdraw_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setWithdrawAmount(BigDecimal withdrawAmount) {
        this.withdrawAmount = withdrawAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.finished_amount
     *
     * @return the value of member.finished_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public BigDecimal getFinishedAmount() {
        return finishedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.finished_amount
     *
     * @param finishedAmount the value for member.finished_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setFinishedAmount(BigDecimal finishedAmount) {
        this.finishedAmount = finishedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.pay_amount
     *
     * @return the value of member.pay_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.pay_amount
     *
     * @param payAmount the value for member.pay_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.useless_amount
     *
     * @return the value of member.useless_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public BigDecimal getUselessAmount() {
        return uselessAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.useless_amount
     *
     * @param uselessAmount the value for member.useless_amount
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setUselessAmount(BigDecimal uselessAmount) {
        this.uselessAmount = uselessAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.finished_orders_number
     *
     * @return the value of member.finished_orders_number
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public Integer getFinishedOrdersNumber() {
        return finishedOrdersNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.finished_orders_number
     *
     * @param finishedOrdersNumber the value for member.finished_orders_number
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setFinishedOrdersNumber(Integer finishedOrdersNumber) {
        this.finishedOrdersNumber = finishedOrdersNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.pay_orders_number
     *
     * @return the value of member.pay_orders_number
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public Integer getPayOrdersNumber() {
        return payOrdersNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.pay_orders_number
     *
     * @param payOrdersNumber the value for member.pay_orders_number
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setPayOrdersNumber(Integer payOrdersNumber) {
        this.payOrdersNumber = payOrdersNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.useless_orders_number
     *
     * @return the value of member.useless_orders_number
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public Integer getUselessOrdersNumber() {
        return uselessOrdersNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.useless_orders_number
     *
     * @param uselessOrdersNumber the value for member.useless_orders_number
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setUselessOrdersNumber(Integer uselessOrdersNumber) {
        this.uselessOrdersNumber = uselessOrdersNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.sub_withdraw
     *
     * @return the value of member.sub_withdraw
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public BigDecimal getSubWithdraw() {
        return subWithdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.sub_withdraw
     *
     * @param subWithdraw the value for member.sub_withdraw
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setSubWithdraw(BigDecimal subWithdraw) {
        this.subWithdraw = subWithdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.tb_user_id
     *
     * @return the value of member.tb_user_id
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getTbUserId() {
        return tbUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.tb_user_id
     *
     * @param tbUserId the value for member.tb_user_id
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setTbUserId(String tbUserId) {
        this.tbUserId = tbUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_time
     *
     * @return the value of member.update_time
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_time
     *
     * @param updateTime the value for member.update_time
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.tag
     *
     * @return the value of member.tag
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.tag
     *
     * @param tag the value for member.tag
     *
     * @mbg.generated Wed Jun 28 09:50:41 CST 2023
     */
    public void setTag(String tag) {
        this.tag = tag;
    }
}